import { OrcamentistaAgentDefinition } from '../../types';

export const agentRegistry: OrcamentistaAgentDefinition[] = [
  {
    id: 'reader_multimodal',
    nome: 'Leitor Multimodal',
    disciplina: 'leitura',
    descricao: 'Lê e extrai dados de PDFs, plantas, memoriais e planilhas enviados.',
    status: 'idle',
    exigeHitl: false,
    podeGerarItens: false,
    podeBloquearConsolidacao: false,
    outputSchema: 'ArquivoLido[]',
  },
  {
    id: 'classificador_documentos',
    nome: 'Classificador de Documentos',
    disciplina: 'classificacao',
    descricao: 'Identifica o tipo de cada arquivo: planta, memorial, especificação, planilha de referência.',
    status: 'idle',
    exigeHitl: false,
    podeGerarItens: false,
    podeBloquearConsolidacao: false,
    outputSchema: 'DocumentoClassificado[]',
  },
  {
    id: 'planner_tecnico',
    nome: 'Planejador Técnico',
    disciplina: 'planejamento',
    descricao: 'Analisa escopo macro e define quais disciplinas e agentes serão acionados.',
    status: 'idle',
    exigeHitl: true,
    podeGerarItens: false,
    podeBloquearConsolidacao: true,
    outputSchema: 'PlanoExecucao',
  },
  {
    id: 'civil_arquitetonico',
    nome: 'Agente Civil / Arquitetônico',
    disciplina: 'civil',
    descricao: 'Levanta serviços de fundação, estrutura de concreto, alvenaria e acabamento civil.',
    status: 'idle',
    exigeHitl: true,
    podeGerarItens: true,
    podeBloquearConsolidacao: true,
    outputSchema: 'AgentOutput',
  },
  {
    id: 'estrutural',
    nome: 'Agente Estrutural',
    disciplina: 'estrutural',
    descricao: 'Analisa projeto estrutural, extrai serviços de armação, formas e concretagem.',
    status: 'idle',
    exigeHitl: true,
    podeGerarItens: true,
    podeBloquearConsolidacao: true,
    outputSchema: 'AgentOutput',
  },
  {
    id: 'eletrica_dados_automacao',
    nome: 'Agente Elétrica / Dados / Automação',
    disciplina: 'eletrica',
    descricao: 'Levanta instalações elétricas, cabeamento estruturado e automação predial.',
    status: 'idle',
    exigeHitl: true,
    podeGerarItens: true,
    podeBloquearConsolidacao: false,
    outputSchema: 'AgentOutput',
  },
  {
    id: 'hidrossanitario',
    nome: 'Agente Hidrossanitário',
    disciplina: 'hidrossanitario',
    descricao: 'Levanta instalações hidráulicas, sanitárias, pluviais e de combate a incêndio hidráulico.',
    status: 'idle',
    exigeHitl: true,
    podeGerarItens: true,
    podeBloquearConsolidacao: false,
    outputSchema: 'AgentOutput',
  },
  {
    id: 'impermeabilizacao',
    nome: 'Agente Impermeabilização',
    disciplina: 'impermeabilizacao',
    descricao: 'Identifica áreas de impermeabilização: lajes, reservatórios, banheiros e coberturas.',
    status: 'idle',
    exigeHitl: false,
    podeGerarItens: true,
    podeBloquearConsolidacao: false,
    outputSchema: 'AgentOutput',
  },
  {
    id: 'climatizacao_exaustao_ventilacao',
    nome: 'Agente Climatização / Exaustão / Ventilação',
    disciplina: 'climatizacao',
    descricao: 'Levanta sistemas de ar-condicionado, exaustão mecânica e ventilação forçada.',
    status: 'idle',
    exigeHitl: true,
    podeGerarItens: true,
    podeBloquearConsolidacao: false,
    outputSchema: 'AgentOutput',
  },
  {
    id: 'ppci_incendio',
    nome: 'Agente PPCI / Combate a Incêndio',
    disciplina: 'ppci',
    descricao: 'Analisa projeto de prevenção e combate a incêndio: sprinklers, detecção e sinalização.',
    status: 'idle',
    exigeHitl: true,
    podeGerarItens: true,
    podeBloquearConsolidacao: true,
    outputSchema: 'AgentOutput',
  },
  {
    id: 'marcenaria_mobiliario_tecnico',
    nome: 'Agente Marcenaria / Mobiliário Técnico',
    disciplina: 'marcenaria',
    descricao: 'Levanta móveis planejados, painéis, bancadas e mobiliário técnico especificado.',
    status: 'idle',
    exigeHitl: false,
    podeGerarItens: true,
    podeBloquearConsolidacao: false,
    outputSchema: 'AgentOutput',
  },
  {
    id: 'vidros_esquadrias_serralheria',
    nome: 'Agente Vidros / Esquadrias / Serralheria',
    disciplina: 'esquadrias',
    descricao: 'Identifica portas, janelas, fachadas em vidro, guarda-corpos e esquadrias de alumínio.',
    status: 'idle',
    exigeHitl: false,
    podeGerarItens: true,
    podeBloquearConsolidacao: false,
    outputSchema: 'AgentOutput',
  },
  {
    id: 'acabamentos',
    nome: 'Agente Acabamentos',
    disciplina: 'acabamentos',
    descricao: 'Levanta revestimentos, pisos, pintura, forros e acabamentos especificados em memorial.',
    status: 'idle',
    exigeHitl: false,
    podeGerarItens: true,
    podeBloquearConsolidacao: false,
    outputSchema: 'AgentOutput',
  },
  {
    id: 'documentacao_aprovacoes',
    nome: 'Agente Documentação / Aprovações',
    disciplina: 'documentacao',
    descricao: 'Identifica custos de aprovações, licenças, ART/RRT, projetos complementares e cartório.',
    status: 'idle',
    exigeHitl: true,
    podeGerarItens: true,
    podeBloquearConsolidacao: true,
    outputSchema: 'AgentOutput',
  },
  {
    id: 'administracao_gestao_obra',
    nome: 'Agente Administração / Gestão de Obra',
    disciplina: 'administracao',
    descricao: 'Estima custos indiretos: equipe administrativa, aluguel de canteiro, seguro e limpeza.',
    status: 'idle',
    exigeHitl: false,
    podeGerarItens: true,
    podeBloquearConsolidacao: false,
    outputSchema: 'AgentOutput',
  },
  {
    id: 'compatibilizacao_tecnica',
    nome: 'Agente Compatibilização Técnica',
    disciplina: 'compatibilizacao',
    descricao: 'Cruza disciplinas para identificar conflitos, sobreposições e omissões de escopo.',
    status: 'idle',
    exigeHitl: true,
    podeGerarItens: false,
    podeBloquearConsolidacao: true,
    outputSchema: 'RelatorioCompatibilizacao',
  },
  {
    id: 'quantitativo',
    nome: 'Agente Quantitativo',
    disciplina: 'quantitativos',
    descricao: 'Consolida e normaliza quantitativos de todas as disciplinas com unidades padronizadas.',
    status: 'idle',
    exigeHitl: true,
    podeGerarItens: false,
    podeBloquearConsolidacao: true,
    outputSchema: 'QuantitativoConsolidado',
  },
  {
    id: 'custos',
    nome: 'Agente Custos',
    disciplina: 'custos',
    descricao: 'Aplica preços de referência (SINAPI, EVIS, cotações) e calcula custos por item.',
    status: 'idle',
    exigeHitl: true,
    podeGerarItens: false,
    podeBloquearConsolidacao: true,
    outputSchema: 'ComposicaoCustos',
  },
  {
    id: 'auditor',
    nome: 'Auditor Técnico',
    disciplina: 'auditoria',
    descricao: 'Verifica consistência cruzada entre disciplinas, quantitativos e custos. Emite alertas.',
    status: 'idle',
    exigeHitl: true,
    podeGerarItens: false,
    podeBloquearConsolidacao: true,
    outputSchema: 'RelatorioAuditoria',
  },
  {
    id: 'hitl_review',
    nome: 'Revisor HITL',
    disciplina: 'hitl',
    descricao: 'Gerencia pontos de validação humana obrigatória antes de consolidar a prévia.',
    status: 'idle',
    exigeHitl: true,
    podeGerarItens: false,
    podeBloquearConsolidacao: true,
    outputSchema: 'HitlPendente[]',
  },
  {
    id: 'consolidador_preview',
    nome: 'Consolidador de Prévia',
    disciplina: 'consolidacao',
    descricao: 'Gera a prévia final do orçamento IA após todas as disciplinas e HITL aprovados.',
    status: 'idle',
    exigeHitl: false,
    podeGerarItens: false,
    podeBloquearConsolidacao: false,
    outputSchema: 'OrcamentistaAiPreview',
  },
];

export function getAgent(id: string): OrcamentistaAgentDefinition | undefined {
  return agentRegistry.find((a) => a.id === id);
}
