import { OrcamentistaHitlIssue } from '../../types';

export const mockOrcamentistaHitlIssues: OrcamentistaHitlIssue[] = [
  {
    id: 'hitl-arch-demolicao-001',
    source_type: 'reader_verifier',
    source_id: 'summary-arch-blocked',
    document_id: 'doc-intake-arq',
    document_name: 'Projeto Arquitetônico.pdf',
    page_number: 3,
    agent_id: 'estrutural',
    issue_type: 'divergencia_reader_verifier',
    severity: 'critica',
    title: 'Demolição sem validação estrutural',
    description:
      'Reader identificou parede a demolir, mas Verifier não descartou interferência estrutural.',
    evidence_summary: 'A-03 marca DEM-01; não há detalhe estrutural associado.',
    recommended_action: 'Manter bloqueado e solicitar validação estrutural antes de qualquer dispatch.',
    status: 'pendente',
    blocks_consolidation: true,
    blocks_dispatch: true,
  },
  {
    id: 'hitl-reader-agreement-001',
    source_type: 'reader_verifier',
    source_id: 'verifier-arch-001',
    document_id: 'doc-intake-arq',
    document_name: 'Projeto Arquitetônico.pdf',
    page_number: 3,
    agent_id: 'compatibilizacao_tecnica',
    issue_type: 'divergencia_reader_verifier',
    severity: 'alta',
    title: 'Baixa concordância Reader/Verifier',
    description: 'Agreement score ficou abaixo do limiar seguro para leitura autônoma.',
    evidence_summary: 'agreement_score mockado: 0.61; status Verifier: BLOCKED.',
    recommended_action: 'Revisar manualmente e reanalisar futuramente com nova evidência.',
    status: 'pendente',
    blocks_consolidation: true,
    blocks_dispatch: true,
  },
  {
    id: 'hitl-quantidade-inferida-001',
    source_type: 'reader_verifier',
    source_id: 'summary-memorial-hitl',
    document_id: 'doc-intake-memorial',
    document_name: 'Memorial Descritivo.pdf',
    page_number: 3,
    agent_id: 'quantitativo',
    issue_type: 'quantidade_inferida',
    severity: 'alta',
    title: 'Quantidade inferida sem origem suficiente',
    description: 'Memorial confirma acabamento, mas não informa área de aplicação.',
    evidence_summary: 'Porcelanato identificado no memorial; área depende de cruzamento com planta.',
    recommended_action: 'Solicitar validação humana antes de permitir quantitativo estimado.',
    status: 'pendente',
    blocks_consolidation: true,
    blocks_dispatch: false,
  },
  {
    id: 'hitl-disciplina-estrutura-001',
    source_type: 'document_inventory',
    source_id: 'inventory-doc-intake-arq',
    document_id: 'doc-intake-arq',
    document_name: 'Projeto Arquitetônico.pdf',
    agent_id: 'estrutural',
    issue_type: 'disciplina_ausente',
    severity: 'alta',
    title: 'Projeto estrutural ausente',
    description: 'Inventário documental não encontrou disciplina estrutural suficiente.',
    evidence_summary: 'Documentos recebidos: arquitetura, memorial e elétrica; estrutura ausente.',
    recommended_action: 'Solicitar projeto estrutural ou manter estimativas estruturais bloqueadas.',
    status: 'pendente',
    blocks_consolidation: true,
    blocks_dispatch: true,
  },
  {
    id: 'hitl-custo-fonte-001',
    source_type: 'costing',
    source_id: 'preview-costos-mock',
    agent_id: 'custos',
    issue_type: 'custo_sem_fonte',
    severity: 'media',
    title: 'Custo sem fonte verificável',
    description: 'Estimativa de instalações apareceu sem base SINAPI/EVIS ou cotação real.',
    evidence_summary: 'Prévia mockada indica custo global, mas sem fonte e competência definida.',
    recommended_action: 'Marcar como verba ou manter fora do orçamento oficial.',
    status: 'pendente',
    blocks_consolidation: true,
    blocks_dispatch: false,
  },
  {
    id: 'hitl-ppci-pendente-001',
    source_type: 'discipline_gap',
    source_id: 'missing-discipline-incendio',
    agent_id: 'ppci_incendio',
    issue_type: 'ppci_pendente',
    severity: 'critica',
    title: 'PPCI pendente',
    description: 'Projeto de prevenção e combate a incêndio não foi recebido ou classificado.',
    evidence_summary: 'Disciplina INCENDIO/PPCI ausente no inventário mockado.',
    recommended_action: 'Solicitar documento obrigatório antes de qualquer consolidação relacionada.',
    status: 'pendente',
    blocks_consolidation: true,
    blocks_dispatch: true,
  },
];
