import { OrcamentistaPipelineStep, OrcamentistaAiPreview } from '../../types';

// Pipeline mockado — Fase 2A
// Nenhum dado real, nenhuma IA real, nenhum item gravado no banco.

export const mockPipelineSteps: OrcamentistaPipelineStep[] = [
  {
    id: 'briefing_inventario',
    nome: 'Briefing e Inventário',
    descricao: 'Coleta de contexto da oportunidade e inventário dos arquivos disponíveis.',
    status: 'concluido',
    progresso: 100,
    agentes: ['reader_multimodal', 'classificador_documentos'],
  },
  {
    id: 'leitura_macro_projeto',
    nome: 'Leitura Macro do Projeto',
    descricao: 'Extração de dados macro: tipo de obra, área total, pavimentos e padrão construtivo.',
    status: 'concluido',
    progresso: 100,
    agentes: ['reader_multimodal'],
  },
  {
    id: 'planejamento_tecnico',
    nome: 'Planejamento Técnico',
    descricao: 'Definição das disciplinas a serem analisadas e roteiro de execução dos agentes.',
    status: 'concluido',
    progresso: 100,
    agentes: ['planner_tecnico'],
  },
  {
    id: 'agentes_dominio',
    nome: 'Agentes de Domínio',
    descricao: 'Execução paralela dos agentes técnicos por disciplina (civil, elétrica, hidro, etc.).',
    status: 'em_execucao',
    progresso: 45,
    agentes: [
      'civil_arquitetonico',
      'estrutural',
      'eletrica_dados_automacao',
      'hidrossanitario',
      'impermeabilizacao',
      'climatizacao_exaustao_ventilacao',
      'ppci_incendio',
      'marcenaria_mobiliario_tecnico',
      'vidros_esquadrias_serralheria',
      'acabamentos',
      'documentacao_aprovacoes',
      'administracao_gestao_obra',
    ],
  },
  {
    id: 'quantitativos',
    nome: 'Quantitativos',
    descricao: 'Consolidação e normalização de quantitativos de todas as disciplinas.',
    status: 'pendente',
    progresso: 0,
    agentes: ['quantitativo', 'compatibilizacao_tecnica'],
  },
  {
    id: 'composicao_custos',
    nome: 'Composição de Custos',
    descricao: 'Aplicação de preços de referência (SINAPI, EVIS) e cálculo de custos por item.',
    status: 'pendente',
    progresso: 0,
    agentes: ['custos'],
  },
  {
    id: 'auditoria_cruzada',
    nome: 'Auditoria Cruzada',
    descricao: 'Verificação de consistência entre disciplinas, quantitativos e custos.',
    status: 'pendente',
    progresso: 0,
    agentes: ['auditor'],
  },
  {
    id: 'hitl',
    nome: 'Revisão HITL',
    descricao: 'Validação humana obrigatória dos pontos críticos antes da consolidação.',
    status: 'pendente',
    progresso: 0,
    agentes: ['hitl_review'],
  },
  {
    id: 'preview_orcamento',
    nome: 'Prévia do Orçamento',
    descricao: 'Geração da prévia IA consolidada. Dados não oficiais — requer aprovação humana.',
    status: 'pendente',
    progresso: 0,
    agentes: ['consolidador_preview'],
  },
  {
    id: 'pronto_para_consolidacao',
    nome: 'Pronto para Consolidação',
    descricao: 'Prévia validada e pronta para consolidação manual no orçamento oficial.',
    status: 'pendente',
    progresso: 0,
    agentes: [],
  },
];

// Prévia IA mockada — Fase 2A
// ATENÇÃO: dados fictícios para demonstração do pipeline.
// Nada aqui é gravado em orcamento_itens.
// Nada aqui alimenta proposta.
// Nada aqui é consolidado automaticamente.

export const mockAiPreview: OrcamentistaAiPreview = {
  origem: 'preview_ia_mock',
  aviso: 'PRÉVIA IA — Dados estimados, não oficiais. Nenhum item gravado no orçamento oficial.',
  confianca: 0.68,
  quantitativos_estimados: 'Estimativa baseada em área total de ~350 m² identificada nos documentos.',
  custos_estimados: 1_240_000,
  premissas: [
    'Padrão construtivo médio-alto conforme memorial descritivo.',
    'Área total de 350 m² distribuída em 2 pavimentos.',
    'Fundação em radier ou sapatas (a confirmar com projeto estrutural).',
    'Instalações elétricas em conformidade com NR10 e NBR 5410.',
    'Não inclui mobiliário decorativo ou obras de arte.',
    'Preços de referência: SINAPI Jun/2025 — base São Paulo.',
  ],
  exclusoes: [
    'Paisagismo e jardinagem.',
    'Mobiliário decorativo e cortinas.',
    'Obras fora do terreno principal.',
    'Taxas de ligação de concessionárias (água, esgoto, energia).',
    'Projeto executivo — somente execução conforme projetos fornecidos.',
  ],
  servicos_sugeridos: [
    {
      codigo: 'CIVIL-001',
      descricao: 'Fundação em radier — concreto armado fck 25 MPa',
      unidade: 'm²',
      quantidade_estimada: 180,
      custo_estimado: 95_400,
      categoria: 'Civil / Estrutural',
      confianca: 0.75,
      origem: 'preview_ia_mock',
      observacoes: 'Tipo de fundação a confirmar com projeto estrutural.',
    },
    {
      codigo: 'CIVIL-002',
      descricao: 'Alvenaria de vedação — bloco cerâmico 14x19x29',
      unidade: 'm²',
      quantidade_estimada: 620,
      custo_estimado: 62_000,
      categoria: 'Civil / Arquitetônico',
      confianca: 0.82,
      origem: 'preview_ia_mock',
    },
    {
      codigo: 'REVC-001',
      descricao: 'Revestimento cerâmico piso — porcelanato 60x60',
      unidade: 'm²',
      quantidade_estimada: 280,
      custo_estimado: 56_000,
      categoria: 'Acabamentos',
      confianca: 0.71,
      origem: 'preview_ia_mock',
      observacoes: 'Padrão médio-alto conforme memorial.',
    },
    {
      codigo: 'ELET-001',
      descricao: 'Instalações elétricas — quadros, fiação e pontos',
      unidade: 'vb',
      quantidade_estimada: 1,
      custo_estimado: 120_000,
      categoria: 'Elétrica',
      confianca: 0.60,
      origem: 'preview_ia_mock',
      observacoes: 'Estimativa global — projeto elétrico não recebido.',
    },
    {
      codigo: 'HIDR-001',
      descricao: 'Instalações hidrossanitárias — água fria, esgoto e pluvial',
      unidade: 'vb',
      quantidade_estimada: 1,
      custo_estimado: 85_000,
      categoria: 'Hidrossanitário',
      confianca: 0.65,
      origem: 'preview_ia_mock',
    },
  ],
  riscos: [
    {
      id: 'risco-001',
      descricao: 'Projeto estrutural não recebido — fundação e estrutura estimadas sem projeto.',
      severidade: 'alta',
      impacto: 'Variação de custo de até 25% na disciplina estrutural.',
      disciplina: 'estrutural',
    },
    {
      id: 'risco-002',
      descricao: 'Projeto elétrico ausente — instalações estimadas por área.',
      severidade: 'media',
      impacto: 'Variação de custo de até 15% na disciplina elétrica.',
      disciplina: 'eletrica',
    },
    {
      id: 'risco-003',
      descricao: 'Solo não investigado — risco de interferência no tipo de fundação.',
      severidade: 'alta',
      impacto: 'Mudança de fundação pode alterar custo em até R$ 150.000.',
      disciplina: 'civil',
    },
    {
      id: 'risco-004',
      descricao: 'PPCI não analisado — projeto de prevenção a incêndio pendente.',
      severidade: 'critica',
      impacto: 'Pode bloquear o habite-se se não contemplado no orçamento.',
      disciplina: 'ppci',
    },
  ],
  pendencias_hitl: [
    {
      id: 'hitl-001',
      titulo: 'Confirmar tipo de fundação',
      motivo: 'Projeto estrutural não recebido. Tipo de fundação foi estimado.',
      disciplina: 'estrutural',
      severidade: 'alta',
      status: 'pendente',
    },
    {
      id: 'hitl-002',
      titulo: 'Validar padrão de acabamentos',
      motivo: 'Memorial descritivo incompleto em relação a revestimentos externos.',
      disciplina: 'acabamentos',
      severidade: 'media',
      status: 'pendente',
    },
    {
      id: 'hitl-003',
      titulo: 'Confirmar escopo de PPCI',
      motivo: 'Projeto de combate a incêndio não recebido — estimativa não disponível.',
      disciplina: 'ppci',
      severidade: 'critica',
      status: 'pendente',
    },
  ],
};
